# Generated by Django 3.2.4 on 2021-06-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librariandb',
            name='id',
        ),
        migrations.AlterField(
            model_name='librariandb',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
