# Generated by Django 3.2.4 on 2021-06-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0002_auto_20210618_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
