# Generated by Django 3.2.4 on 2021-06-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0004_auto_20210619_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('book_name', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('fine', models.IntegerField(default=0)),
            ],
        ),
    ]
