# Generated by Django 3.2.4 on 2021-06-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0005_issuereturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
