# Generated by Django 3.2.4 on 2021-06-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0006_auto_20210620_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereturn',
            name='book_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
