# Generated by Django 3.2.4 on 2021-06-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210618_1249'),
        ('Librarian', '0007_issuereturn_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereturn',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Librarian.librariandb'),
        ),
        migrations.AlterField(
            model_name='issuereturn',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentdb'),
        ),
    ]
