# Generated by Django 3.2.4 on 2021-06-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0008_auto_20210620_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereturn',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Librarian.books'),
        ),
    ]
