# Generated by Django 3.2.4 on 2021-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_no', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField(max_length=10)),
                ('shift', models.CharField(max_length=20)),
            ],
        ),
    ]
