# Generated by Django 3.2.4 on 2021-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='enroll_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
