# Generated by Django 3.2.4 on 2021-06-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210612_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='enroll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
